//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormFlow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlowRun
    {
        public FlowRun()
        {
            this.FlowSteps = new HashSet<FlowStep>();
        }
    
        public System.Guid ID { get; set; }
        public Nullable<System.DateTime> StartedAt { get; set; }
        public Nullable<System.Guid> CurrentStepID { get; set; }
    
        public virtual Step CurrentStep { get; set; }
        public virtual ICollection<FlowStep> FlowSteps { get; set; }
    }
}
