//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormFlow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transition
    {
        public System.Guid ID { get; set; }
        public string Description { get; set; }
        public System.Guid FromStepID { get; set; }
        public Nullable<System.Guid> ToStepID { get; set; }
        public System.Guid TranistionTypeID { get; set; }
    
        public virtual Step FromStep { get; set; }
        public virtual Step ToStep { get; set; }
        public virtual TransitionType TransitionType { get; set; }
    }
}
